{% set name = "neptune-tensorflow-keras" %}
{% set version = "0.9.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/neptune-ai/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 990681f8657cbe9e533daee98a71a305d3f1d26f466deeb9bfa5926f9c440a61

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - neptune-client >=0.9
    - python >=3.6
    - tensorflow >=2.0

test:
  imports:
    - neptune_tensorflow_keras
    - neptune_tensorflow_keras.impl

about:
  home: https://neptune.ai/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Neptune Client integration with Tensorflow and Keras
  doc_url: https://github.com/neptune-ai/neptune-tensorflow-keras/blob/master/README.md
  dev_url: https://github.com/neptune-ai/neptune-tensorflow-keras

extra:
  recipe-maintainers:
    - aniezurawski
    - HubertJaworski
    - pitercl
    - PiotrJander
    - shnela
    - pkasprzyk
